@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version = '3.5.0'
String imgTag  = "v" + version

imagePipeline(
        branchPattern: new BranchPattern(master: "oracle/release/" + version, feature: '(?!^release/.*$)(^.*$)'),
        containers: [('container-registry.oracle.com/olcne/prometheus:' + imgTag): 'olcne/prometheus:' + imgTag],
        platforms: ['ol9'],
        architectures: ['x86_64', 'aarch64'],
        publishImage: true,
        yumOL9Repos: ['ol9_codeready_builder'],
        ol9ModulesToEnable: ['nodejs:22'],
        buildScript: "sh olm/build-image.sh"
)
