{{{$version := printf "%s.%s.%s" .major .minor .patch }}}
@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version = '{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}'
String imgTag  = "v" + version

olcnePipeline(
        branchPattern: new BranchPattern(master: "oracle/release/" + version, feature: '(?!^release/.*$)(^.*$)'),
        containers: [('container-registry.oracle.com/olcne/prometheus:' + imgTag): 'olcne/prometheus:' + imgTag],
        platforms: ['ol8', 'ol9'],
        architectures: ['x86_64', 'aarch64'],
        golang: '1.23.9',
        publishImage: true,
        yumOL8Repos: ['ol8_appstream', 'ol8_codeready_builder'],
        ol8ModulesToEnable: ['nodejs:22'],
        ol9ModulesToEnable: ['nodejs:22'],
        customPlatformSteps: [
                ol9: [container: [enabled: true], buildContainerRpms: [enabled: true]],
        ]
)
