
@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version = '3.7.2'
String imgTag  = "v" + version

imagePipeline(
        branchPattern: new BranchPattern(master: "oracle/release/" + version, feature: '(?!^release/.*$)(^.*$)'),
        containers: [('container-registry.oracle.com/olcne/prometheus:' + imgTag): 'olcne/prometheus:' + imgTag],
        platforms: ['ol9'],
        architectures: ['x86_64', 'aarch64'],
        buildScript: "sh olm/build-image.sh"
)
